server:
  port: 8080
  context-path: /srui
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      exclude: static/**
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
  thymeleaf:
    mode: HTML
    cache: false

## mybatis ##
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  executorType: simple
## logging ##
logging:
  level:
    ROOT: info
  config: classpath:log4j2.yml

endpoints:
  actuator:
    enabled: true