package com.xstudio.spring.model;

import com.xstudio.common.BaseModelObject;
import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table application_role
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Role extends BaseModelObject implements Serializable {
    /**
     * Database Column Remarks:
     *   role id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_role.role_id
     *
     * @mbg.generated
     */
    private Long roleId;

    /**
     * Database Column Remarks:
     *   role key
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_role.role_key
     *
     * @mbg.generated
     */
    private String roleKey;

    /**
     * Database Column Remarks:
     *   role name
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_role.role_name
     *
     * @mbg.generated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table application_role
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_role.role_id
     *
     * @return the value of application_role.role_id
     *
     * @mbg.generated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_role.role_id
     *
     * @param roleId the value for application_role.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_role.role_key
     *
     * @return the value of application_role.role_key
     *
     * @mbg.generated
     */
    public String getRoleKey() {
        return roleKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_role.role_key
     *
     * @param roleKey the value for application_role.role_key
     *
     * @mbg.generated
     */
    public void setRoleKey(String roleKey) {
        this.roleKey = roleKey == null ? null : roleKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_role.role_name
     *
     * @return the value of application_role.role_name
     *
     * @mbg.generated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_role.role_name
     *
     * @param roleName the value for application_role.role_name
     *
     * @mbg.generated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }
}