package com.xstudio.spring.model;

import com.xstudio.common.BaseModelObject;
import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table application_sql_log
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SqlLog extends BaseModelObject implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_sql_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_sql_log.method
     *
     * @mbg.generated
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_sql_log.table_name
     *
     * @mbg.generated
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_sql_log.actor_id
     *
     * @mbg.generated
     */
    private Long actorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_sql_log.client_ip
     *
     * @mbg.generated
     */
    private String clientIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_sql_log.user_agent
     *
     * @mbg.generated
     */
    private String userAgent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_sql_log.server_name
     *
     * @mbg.generated
     */
    private String serverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_sql_log.server_port
     *
     * @mbg.generated
     */
    private String serverPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application_sql_log.statment
     *
     * @mbg.generated
     */
    private String statment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table application_sql_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_sql_log.id
     *
     * @return the value of application_sql_log.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_sql_log.id
     *
     * @param id the value for application_sql_log.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_sql_log.method
     *
     * @return the value of application_sql_log.method
     *
     * @mbg.generated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_sql_log.method
     *
     * @param method the value for application_sql_log.method
     *
     * @mbg.generated
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_sql_log.table_name
     *
     * @return the value of application_sql_log.table_name
     *
     * @mbg.generated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_sql_log.table_name
     *
     * @param tableName the value for application_sql_log.table_name
     *
     * @mbg.generated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_sql_log.actor_id
     *
     * @return the value of application_sql_log.actor_id
     *
     * @mbg.generated
     */
    public Long getActorId() {
        return actorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_sql_log.actor_id
     *
     * @param actorId the value for application_sql_log.actor_id
     *
     * @mbg.generated
     */
    public void setActorId(Long actorId) {
        this.actorId = actorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_sql_log.client_ip
     *
     * @return the value of application_sql_log.client_ip
     *
     * @mbg.generated
     */
    public String getClientIp() {
        return clientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_sql_log.client_ip
     *
     * @param clientIp the value for application_sql_log.client_ip
     *
     * @mbg.generated
     */
    public void setClientIp(String clientIp) {
        this.clientIp = clientIp == null ? null : clientIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_sql_log.user_agent
     *
     * @return the value of application_sql_log.user_agent
     *
     * @mbg.generated
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_sql_log.user_agent
     *
     * @param userAgent the value for application_sql_log.user_agent
     *
     * @mbg.generated
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent == null ? null : userAgent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_sql_log.server_name
     *
     * @return the value of application_sql_log.server_name
     *
     * @mbg.generated
     */
    public String getServerName() {
        return serverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_sql_log.server_name
     *
     * @param serverName the value for application_sql_log.server_name
     *
     * @mbg.generated
     */
    public void setServerName(String serverName) {
        this.serverName = serverName == null ? null : serverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_sql_log.server_port
     *
     * @return the value of application_sql_log.server_port
     *
     * @mbg.generated
     */
    public String getServerPort() {
        return serverPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_sql_log.server_port
     *
     * @param serverPort the value for application_sql_log.server_port
     *
     * @mbg.generated
     */
    public void setServerPort(String serverPort) {
        this.serverPort = serverPort == null ? null : serverPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application_sql_log.statment
     *
     * @return the value of application_sql_log.statment
     *
     * @mbg.generated
     */
    public String getStatment() {
        return statment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application_sql_log.statment
     *
     * @param statment the value for application_sql_log.statment
     *
     * @mbg.generated
     */
    public void setStatment(String statment) {
        this.statment = statment == null ? null : statment.trim();
    }
}